# Generated by Django 4.2.17 on 2024-12-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0035_auto_20230822_2208_squashed_0036_auto_20240311_1028"),
        ("cmsplugin_filer_image", "0010_auto_20191127_1058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filerimage",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
